export const composeButton = "//div[text()='Compose']"
export const toButton = "//input[@aria-label='To recipients']" 
export const subject = "//input[@name='subjectbox']"
export const textBox = "//div[@role='textbox']"
export const sendButton = "//div[text()='Send']"
