export const signinButton = "//a[text()='Sign in']"
export const appIcon = "//a[@aria-label='Google apps']"
export const gmailBtn = "//iframe[@name='app']"
export const mail = "//input[@type='email']"
export const password = "//input[@type='password']"
export const nextButton = "//span[text()='Next']"
export const phoneNumber = "//span[text()='Phone']"
